version: '3'
services:
  api:
    build: .
    ports:
      - ${PORT}:3000
    environment:
      MONGO_URI: mongodb://mongo/${MONGO_DB}
      HOST: "0.0.0.0"
      PORT: ${PORT}
  mongo:
    image: mongo
